import type { BattleState, GameState, CampState } from '../../types';
import {
  BattlePhase,
  DrillStep,
  GamePhase,
  MoraleThreshold,
  HealthState,
  FatigueTier,
  MilitaryRank,
  NPCRole,
} from '../../types';

/** Minimal BattleState with sensible defaults. Override any field via `overrides`. */
export function mockBattleState(overrides: Partial<BattleState> = {}): BattleState {
  return {
    phase: BattlePhase.Line,
    drillStep: DrillStep.Fire,
    battlePart: 1,
    player: {
      name: 'Pierre',
      valor: 40,
      musketry: 35,
      elan: 35,
      strength: 40,
      endurance: 40,
      constitution: 45,
      charisma: 30,
      intelligence: 30,
      awareness: 35,
      morale: 60,
      maxMorale: 100,
      moraleThreshold: MoraleThreshold.Wavering,
      health: 80,
      maxHealth: 125,
      healthState: HealthState.Unhurt,
      stamina: 200,
      maxStamina: 400,
      fatigue: 0,
      maxFatigue: 400,
      fatigueTier: FatigueTier.Fresh,
      musketLoaded: true,
      alive: true,
      routing: false,
      fumbledLoad: false,
      soldierRep: 50,
      officerRep: 50,
      napoleonRep: 0,
      frontRank: false,
      canteenUses: 3,
    },
    enemy: {
      range: 100,
      strength: 300,
      quality: 'line',
      morale: 'steady',
      lineIntegrity: 50,
      artillery: false,
      cavalryThreat: false,
    },
    line: {
      leftNeighbour: { id: 'pierre', name: 'Pierre', rank: 'private', valor: 30, morale: 60, maxMorale: 100, threshold: MoraleThreshold.Wavering, alive: true, wounded: false, routing: false, musketLoaded: true, relationship: 50 },
      rightNeighbour: { id: 'jb', name: 'Jean-Baptiste', rank: 'private', valor: 20, morale: 50, maxMorale: 100, threshold: MoraleThreshold.Wavering, alive: true, wounded: false, routing: false, musketLoaded: true, relationship: 40 },
      officer: { name: 'Lt. Durand', rank: 'lieutenant', alive: true, wounded: false, mounted: false, status: 'commanding' },
      lineIntegrity: 70,
      lineMorale: 'steady',
      drumsPlaying: true,
      ncoPresent: true,
      casualtiesThisTurn: 0,
    },
    soldiers: [],
    officers: [],
    log: [],
    availableActions: [],
    pendingMoraleChanges: [],
    turn: 10,
    volleysFired: 5,
    scriptedVolley: 1,
    chargeEncounter: 0,
    autoPlayActive: false,
    autoPlayVolleyCompleted: 0,
    crisisTurn: 0,
    battleOver: false,
    outcome: 'victory',
    batteryCharged: false,
    meleeStage: 0,
    wagonDamage: 0,
    gorgeMercyCount: 0,
    graceEarned: false,
    ...overrides,
  } as BattleState;
}

/** Minimal GameState. Override player/npcs/battleState/campState via `overrides`. */
export function mockGameState(overrides: Partial<GameState> = {}): GameState {
  return {
    phase: GamePhase.Battle,
    player: {
      name: 'Pierre',
      rank: MilitaryRank.Private,
      valor: 40,
      musketry: 35,
      elan: 35,
      strength: 40,
      endurance: 40,
      constitution: 45,
      charisma: 30,
      intelligence: 30,
      awareness: 35,
      health: 100,
      morale: 100,
      stamina: 100,
      grace: 0,
      soldierRep: 50,
      officerRep: 50,
      napoleonRep: 0,
      frontRank: false,
      equipment: {
        musket: 'Charleville 1777',
        bayonet: 'Socket bayonet',
        musketCondition: 70,
        uniformCondition: 50,
      },
    },
    npcs: [
      {
        id: 'pierre',
        name: 'Pierre',
        role: NPCRole.Neighbour,
        rank: MilitaryRank.Private,
        relationship: 50,
        alive: true,
        wounded: false,
        morale: 60,
        maxMorale: 100,
        valor: 30,
      },
      {
        id: 'jb',
        name: 'Jean-Baptiste',
        role: NPCRole.Neighbour,
        rank: MilitaryRank.Private,
        relationship: 40,
        alive: true,
        wounded: false,
        morale: 50,
        maxMorale: 100,
        valor: 20,
      },
    ],
    campaign: {
      battlesCompleted: 0,
      currentBattle: 'rivoli',
      nextBattle: 'castiglione',
      daysInCampaign: 1,
    },
    ...overrides,
  } as unknown as GameState;
}

/** Minimal CampState for camp-related tests. */
export function mockCampState(overrides: Partial<CampState> = {}): CampState {
  return {
    day: 1,
    actionsRemaining: 15,
    actionsTotal: 15,
    health: 80,
    stamina: 70,
    morale: 60,
    conditions: {
      location: 'Rivoli Plateau',
      weather: 'cold',
      supplyLevel: 'scarce',
      campMorale: 'low',
    },
    log: [],
    triggeredEvents: [],
    pendingEvent: null,
    ...overrides,
  } as unknown as CampState;
}
